def even_fib(limit):
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    """
    
    a = 0
    b = 1
    even = []

    for num in range(1, limit + 1):
        a, b = b, a + b
        if b % 2 == 0:
            even.append(b)

    return(sum(even))
